export const DATA_PRODUCTS = [
  { 
    id: "1312341",
    sku:"1233314",
    image:"/assets/images/product/example1.png",
    name: "Skin serum",
    description: "Product ini menggunakan item yang harus dibuat",
    price: 2000000,
    stock:10,
    type: "product",
    sold:20000,
    is_active:true,
    promo :{
        id:1,
        quota:140,
        quota_availlable:12,
        quota_used:128,
        discount:200000,
        discount_type:"persen",
    },
  },
  { 
    id: "1312342",
    sku:"ALgae",
    name: "ALgae suntik",
    description: "Product ini menggunakan item",
    price: 2000000,
    stock:20,
    type:"product",
    sold:2100,
    is_active:false,
    variants: [
        {
            id:2,
            name:"500 ml",
            price: 3000000,
            stock:200,
        },
        {
            id:2,
            name:"500 ml",
            price: 2500000,
            stock:300
        }
    ]
  },
  { 
    id: "1312343",
    name: "SALMON DNA",
    image:"/assets/images/product/example3.jpeg",
    description: "Product ini menggunakan item",
    price: 200000,
    sold:30000,
    stock:10,
    type: "treatment",
    is_active:true,
  },  { 
    id: "1312331",
    image:"/assets/images/product/example4.jpeg",
    description: "Product ini menggunakan item",
    name: "Skin serum",
    price: 2300000,
    type: "product",
    stock:10,
    sold:2000,
    is_active:true,
    promo :{
        id:1
    },
  },
  { 
    id: "1312141",
    image:"/assets/images/product/example5.jpeg",
    description: "Product ini menggunakan item",
    name: "Skin serum",
    price: 98000,
    type: "product",
    sold:20003,
    stock:10,
    is_active:true,
    promo :{
        id:1,
        quota:140,
        quota_availlable:12,
        quota_used:128,
        discount:20000,
        discount_type:"persen",
    },
  },
  { 
    id: "13121421",
    image:"/assets/images/product/example5.jpeg",
    description: "Product ini menggunakan item",
    name: "Skin serum",
    price: 98000,
    type: "product",
    sold:20003,
    stock:10,
    is_active:true,
    promo :{
        id:1,
        quota:140,
        quota_availlable:12,
        quota_used:128,
        discount:20000,
        discount_type:"persen",
    },
  },
  { 
    id: "13121341",
    image:"/assets/images/product/example4.jpeg",
    description: "Product ini menggunakan item",
    name: "Skin serum",
    price: 98000,
    type: "product",
    sold:20003,
    stock:10,
    is_active:true,
    promo :{
        id:1,
        quota:140,
        quota_availlable:12,
        quota_used:128,
        discount:20000,
        discount_type:"persen",
    },
  },
  { 
    id: "12312141",
    image:"/assets/images/product/example2.jpeg",
    description: "Product ini menggunakan item",
    name: "Skin serum",
    price: 98000,
    type: "product",
    sold:20003,
    stock:10,
    is_active:true,
    promo :{
        id:1,
        quota:140,
        quota_availlable:12,
        quota_used:128,
        discount:20000,
        discount_type:"persen",
    },
  },
  { 
    id: "12112141",
    image:"/assets/images/product/example2.jpeg",
    description: "Product ini menggunakan item",
    name: "Skin serum",
    price: 98000,
    type: "product",
    sold:20003,
    stock:10,
    is_active:true,
    promo :{
        id:1,
        quota:140,
        quota_availlable:12,
        quota_used:128,
        discount:20000,
        discount_type:"persen",
    },
  },
  { 
    id: "13123412",
    sku:"Skin Serum",
    name: "Skin serum suntik",
    description: "Product ini menggunakan item",
    price: 2000000,
    stock:20,
    type:"product",
    sold:2100,
    is_active:false,
    variants: [
        {
            id:2,
            name:"500 ml",
            price: 3000000,
            stock:200,
        },
        {
            id:2,
            name:"500 ml",
            price: 2500000,
            stock:300
        }
    ]
  },
]